version: 0.2

env:
  variables:
    AWS_REGION: us-east-1
    GITHUB_OWNER: saifudheenvk
    GITHUB_REPO: product-service-codebuild-codepipeline-appsync-lamda
    GITHUB_BRANCH: master


phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo "Installing dependencies..."
  build:
    commands:
      - echo "Building the application..."
      - sam build
  post_build:
    commands:
      - echo "Deploying application..."
      - export GITHUB_TOKEN=$(aws secretsmanager get-secret-value --secret-id arn:aws:secretsmanager:us-east-1:597088052511:secret:GITHUB_TOKEN-Qk0XcT --query SecretString --output text)
      - sam deploy --stack-name product-service --capabilities CAPABILITY_IAM --region $AWS_REGION --parameter-overrides Environment=prod GitHubOwner=$GITHUB_OWNER GitHubRepo=$GITHUB_REPO GitHubBranch=$GITHUB_BRANCH GitHubToken=$GITHUB_TOKEN  --s3-bucket aws-sam-cli-managed-default-samclisourcebucket-lb1lqslyylxs

artifacts:
  files:
    - '**/*'
  discard-paths: yes
